zackify/cli.rs

domains/wte

Removed directory in CNAME

---

domains/silver

Link to the project: https://github.com/silver-prompt/silver

Add silver

---

domains/unused

Adds [unused](https://unused.codes/)

Add unused

---

domains/sheldon

Add [sheldon](https://github.com/rossmacarthur/sheldon)

Add sheldon

---

domains/brainease

Hey, this is exactly what I was looking for...
I'll use the subdomain for my _"programming language"_.
https://github.com/arthurfiorette/brainease

brainease.cli.rs

---

README.md

being more specific

---

domains/fibora

Repo https://github.com/UltiRequiem/fibora
Should I put `ultirequiem.github.io/fibora` or just `ultirequiem.github.io` ?

fibora.cli.rs

---

domains/systeroid

Project: https://github.com/orhun/systeroid

Add systeroid

---

domains/trippy

Project: https://github.com/fujiapple852/trippy
Thank you for providing this great service to the community.

add trippy

---

domains/colmena

Project: https://github.com/zhaofengli/colmena

Add colmena

---

domains/lychee

Project: https://github.com/lycheeverse/lychee
Would love to get this added to your repo. Thanks for providing that service. 😊

Add lychee

---

domains/getanswe

This PR adds a subdomain for [schneiderfelipe/getanswe.rs](https://github.com/schneiderfelipe/getanswe.rs), a suite of command-line applications for creating large language model applications such as question-answering, summarization, etc.

Create getanswe (getanswe.cli.rs)

---

domains/exilvm

This adds a subdomain for my personal page web app written in Rust: [exilvm/exilvmlinuz](https://github.com/exilvm/exilvmlinuz)

Add `exilvm` subdomain

---

domains/rustic

Hey there,
this adds `rustic.cli.rs`, a tool to create deduplicated, encrypted backups.
Thank you (:

Add rustic

---

domains/bos

Learn more about BOS: https://near.org
https://bos.cli.rs will be a homepage for https://github.com/bos-cli-rs/bos-cli-rs project

Create bos.cli.rs which stands for NEAR Blockchain Operating System CLI

---

domains/rustyink

It's a static site generator written in Rust.
Thank you, you're awesome!

Add rustyink

---

domains/sr

Hi, I'm a student lately I'm interested in learning the Rust language. I'm trying to develop a static website with Rustyink and I want to host it on a github page. Then I found your website cli.rs and it said that you bought cli.rs for the community. Can I apply for my domain?

Create sr domain

---

domains/hatsu

https://github.com/importantimport/hatsu

hatsu.cli.rs

---

domains/daktilo

For my upcoming project: https://github.com/orhun/daktilo

Add daktilo

---

domains/nodemore
domains/sandbox

**Sandbox**
Origin URL: https://github.com/the-sandbox-project/sandbox
Requested URL: https://sandbox.cli.rs
A Command-Line Sandbox Tester for Different Programming Languages.
**Nodemore**
Origin URL: https://github.com/WillKirkmanM/nodemore
Requested URL: https://nodemore.cli.rs
A Rust Based Hard Disk Reliever for NodeJS Node Modules

Added: The Sandbox Project & Nodemore to Domain List

---

domains/pls

This PR adds the domain mapping for `pls`.
Source code: https://github.com/pls-rs/pls
Documentation: https://pls-rs.github.io/pls

Add domain mapping for `pls`

---

domains/pace

Hey there, I would like to add our org if that's possible. Thank you! 💯

Add pace to domains

---

domains/bloc

I am moving away from GitHub. As such, this record will become defunct.

Remove blocc.cli.rs
